[1x]
startYear = 2014
midPoint = 2019
endYear = 2024
startDate = "2014-01-01"
midPointDate="2019-01-01"
endDate = "2023-12-31"
LoanDate = "2023-10-01"
cust_rate = 0.8
loan_rate = 0.2
prob_blocked = 0.01
savingaccount_datapath="savingAccount.csv"
checkingaccount_datapath="checkingAccount.csv"
tranfer_datapath="transfer.csv"
checking_datapath="checking.csv"
loanapps_datapath="loanApps.csv"
loantrans_datapath="loanTrans.csv"
customer_number = 300000
customer_age_lower = 18
customer_age_upper = 60
customer_loanbalance = 10000
customer_checkingbalance = 5000
customer_savingbalance = 2000
customer_datapath = "customer.csv"
company_loanbalance = 1000000
company_checkingbalance = 100000
company_savingbalance = 10000
company_number = 2000
company_size_lower = 10
company_size_upper = 100
company_datapath = "company.csv"
transfer_number = 6000000
checking_number = 600000
loanapps_number = 600000
loantrans_number = 600000
[10x]
startYear = 2014
midPoint = 2019
endYear = 2024
startDate = "2014-01-01"
midPointDate="2019-01-01"
endDate = "2023-12-31"
LoanDate = "2023-10-01"
cust_rate = 0.8
loan_rate = 0.2
prob_blocked = 0.01
savingaccount_datapath="savingAccount.csv"
checkingaccount_datapath="checkingAccount.csv"
tranfer_datapath="transfer.csv"
checking_datapath="checking.csv"
loanapps_datapath="loanApps.csv"
loantrans_datapath="loanTrans.csv"
customer_number = 3000000
customer_age_lower = 18
customer_age_upper = 60
customer_loanbalance = 10000
customer_checkingbalance = 5000
customer_savingbalance = 2000
customer_datapath = "customer.csv"
company_loanbalance = 1000000
company_checkingbalance = 100000
company_savingbalance = 10000
company_number = 20000
company_size_lower = 10
company_size_upper = 100
company_datapath = "company.csv"
transfer_number = 60000000
checking_number = 6000000
loanapps_number = 6000000
loantrans_number = 6000000
[100x]
startYear = 2014
midPoint = 2019
endYear = 2024
startDate = "2014-01-01"
midPointDate="2019-01-01"
endDate = "2023-12-31"
LoanDate = "2023-10-01"
cust_rate = 0.8
loan_rate = 0.2
prob_blocked = 0.01
savingaccount_datapath="savingAccount.csv"
checkingaccount_datapath="checkingAccount.csv"
tranfer_datapath="transfer.csv"
checking_datapath="checking.csv"
loanapps_datapath="loanApps.csv"
loantrans_datapath="loanTrans.csv"
customer_number = 30000000
customer_age_lower = 18
customer_age_upper = 60
customer_loanbalance = 10000
customer_checkingbalance = 5000
customer_savingbalance = 2000
customer_datapath = "customer.csv"
company_loanbalance = 1000000
company_checkingbalance = 100000
company_savingbalance = 10000
company_number = 200000
company_size_lower = 10
company_size_upper = 100
company_datapath = "company.csv"
transfer_number = 600000000
checking_number = 60000000
loanapps_number = 60000000
loantrans_number = 60000000
[1000x]
startYear = 2014
midPoint = 2019
endYear = 2024
startDate = "2014-01-01"
midPointDate="2019-01-01"
endDate = "2023-12-31"
LoanDate = "2023-10-01"
cust_rate = 0.8
loan_rate = 0.2
prob_blocked = 0.01
savingaccount_datapath="savingAccount.csv"
checkingaccount_datapath="checkingAccount.csv"
tranfer_datapath="transfer.csv"
checking_datapath="checking.csv"
loanapps_datapath="loanApps.csv"
loantrans_datapath="loanTrans.csv"
customer_number = 300000000
customer_age_lower = 18
customer_age_upper = 60
customer_loanbalance = 10000
customer_checkingbalance = 5000
customer_savingbalance = 2000
customer_datapath = "customer.csv"
company_loanbalance = 1000000
company_checkingbalance = 100000
company_savingbalance = 10000
company_number = 2000000
company_size_lower = 10
company_size_upper = 100
company_datapath = "company.csv"
transfer_number = 6000000000
checking_number = 600000000
loanapps_number = 600000000
loantrans_number = 600000000